---
title: "Dengue: Detección y vacunación"
format: 
  revealjs:
    slide-number: true
    logo: unr.jpeg
    embed-resources: true
    width: 1500
    margin: 0.0005
    title-block-style: center
author: "Roncaglia Andrés - Santini Franco"
echo: false
warning: false
message: false
---

## Introducción

<style>
.reveal h2 {
  text-align: center;
}
</style>


El dengue es una enfermedad febril que se transmite a través de la picadura de mosquitos (*aedes aegypti*) infectados. Existen 4 serotipos del virus (DENV) que circulan mundialmente, causando un estimado de 390 millones de infecciones anuales. En argentina el virus del dengue ha experimentado
un aumento en los últimos años y en Rosario en específico es una problemática cíclica.

## Análisis de artículos relacionados

. . .

- *Live, Attenuated, Tetravalent Butantan–Dengue Vaccine in Children and Adults*

  *The new england journal of medicine*

  Score: 96,2

. . .

- *Effectiveness and safety of the tetravalent TAK-003 Dengue vaccine: a systematic review*

  MEDICINA (Buenos Aires)
  
  Score: 0,6

::: footer
Fuente: Cite Factor
:::

## Objetivos

::: columns
::: {.column width="50%"}

<center>
**Butantan–Dengue**
</center>

<justify>
Evaluar la eficacia general y seguridad de la vacuna **Butantan-DV** en personas sintomáticas y virológicamente confirmadas de cualquier serotipo de dengue sin importar el estado serológico al comienzo del estudio.
</justify>

:::
::: {.column width="50%"}
<center>
**TAK-003**
</center>

Evaluar la efectividad y seguridad de la vacuna tretavalente TAK-003 contra el dengue, sin importar la exposición previa al virus.
:::
:::












